const firstName = document.querySelector('.firtname')
const lastName = document.querySelector('.lastname')
const street = document.querySelector('.street')
const state = document.querySelector('.state')
const zipCode = document.querySelector('.zipcode')
